# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: parkingrightdb
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080